market/market/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('', include('stock.urls')),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('admin/', admin.site.urls),
]

admin.site.site_header = 'MiniMart'
admin.site.site_title = 'MiniMart'

market/stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'

urlpatterns = [
    path('', views.home, name='home'),

    path('products/', views.ProductIndexView.as_view(),
         name='product_index'),
    path('products/new', views.ProductCreateView.as_view(),
         name='product_create'),
    path('products/<int:pk>/edit', views.ProductUpdateView.as_view(),
         name='product_update'),

    path('purchases/', views.PurchaseIndexView.as_view(),
         name='purchase_index'),
    path('purchases/new', views.PurchaseCreateView.as_view(),
         name='purchase_create'),
    path('purchases/<int:pk>/edit', views.PurchaseUpdateView.as_view(),
         name='purchase_update'),
]

market/stock/models.py
from django.db import models
from django.core.validators import MinValueValidator


class Product(models.Model):
    """
    Classe que representa os produtos que serão cadastrados.
    """
    name = models.CharField('nome', max_length=200, unique=True)
    average_cost = models.DecimalField('custo médio', default=0, max_digits=10,
                                       decimal_places=2, editable=False)

    def __str__(self):
        return self.name

    def recalculate_average(self):
        """
        Recalcula o custo médio do produto com base nas compras associadas.
        Método utilizado no arquivo signals.py.
        """
        if not self.purchase_set.all():
            # O produto não tem compras associadas
            self.average_cost = 0
            self.save()
            return

        # O produto tem compras associadas
        total_amount = 0
        total_cost = 0
        for p in self.purchase_set.values('cost_per_item', 'amount'):
            total_cost += p['cost_per_item'] * p['amount']
            total_amount += p['amount']
        self.average_cost = total_cost / total_amount
        self.save()

    class Meta:
        verbose_name = 'produto'


class Purchase(models.Model):
    """
    Classe que representa cada compra de um produto.
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                verbose_name='produto')
    amount = models.PositiveIntegerField('quantidade')
    cost_per_item = models.DecimalField('custo por item', max_digits=10,
                                        decimal_places=2,
                                        validators=[MinValueValidator(0)])

    class Meta:
        verbose_name = 'compra'
        ordering = ('product',)

market/stock/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Product, Purchase


def home(request):
    return render(request, 'stock/home.html')


class ProductIndexView(generic.ListView):
    model = Product


class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    login_url = '/login/'
    model = Product
    fields = ['name']
    success_url = reverse_lazy('stock:product_index')


class ProductUpdateView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login/'
    model = Product
    fields = ['name']
    success_url = reverse_lazy('stock:product_index')


class PurchaseIndexView(generic.ListView):
    model = Purchase


class PurchaseCreateView(LoginRequiredMixin, generic.CreateView):
    login_url = '/login/'
    model = Purchase
    fields = ['product', 'amount', 'cost_per_item']
    success_url = reverse_lazy('stock:purchase_index')


class PurchaseUpdateView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login/'
    model = Purchase
    fields = ['product', 'amount', 'cost_per_item']
    success_url = reverse_lazy('stock:purchase_index')

market/market/templates/market/base.html
{% load static %}

<html>
    <head>
        <title>MiniMart | {% block pagetitle %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'market/style.css' %}">
    </head>
    <body>
        <header>
            <h1>MiniMart</h1>
            <nav>
                <a href="{% url 'stock:home' %}">Início</a>
                <a href="{% url 'stock:product_index' %}">Produtos</a>
                <a href="{% url 'stock:purchase_index' %}">Compras</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}">Sair</a>
                {% else %}
                    <a href="{% url 'login' %}">Entrar</a>
                {% endif %}
            </nav>
        </header>
        <section id="content">
            {% block content %}
            {% endblock %}
        </section>
    </body>
</html>

market/stock/templates/stock/home.html
{% extends 'market/base.html' %}

{% block pagetitle %}Início{% endblock %}

{% block content %}

    <h2>Bem vindo!</h2>

    <p class="intro">Esse projeto é um pequeno sistema web que simula um sistema de registro de estoque de um supermercado. Foi desenvolvido para o processo seletivo da WPensar, pela Carolina Ransatto.</p>

    <p>Para acessar como administrador, <a href="/admin">clique aqui</a>.</p>

{% endblock %}

market/stock/templates/stock/product_form.html
{% extends 'market/base.html' %}

{% block pagetitle %}
    {% if product %}
        Editar {{ product.name }}
    {% else %}
        Novo produto
    {% endif %}
{% endblock %}


{% block content %}
    <h3>
        {% if product %}
            Editar {{ product.name }}
        {% else %}
            Novo produto
        {% endif %}
    </h3>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if product %}
            <p>Custo médio: {{ product.average_cost }}</p>
        {% endif %}
        <input type="submit" value="Salvar" />
    </form>

    <a href="{% url 'stock:product_index' %}" class="cancel">Cancelar</a>
{% endblock %}

market/stock/templates/stock/product_list.html
{% extends 'market/base.html' %}
{% load static %}

{% block pagetitle %}Produtos{% endblock %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Custo médio (R$)</th>
                <th>
                    <a href="{% url 'stock:product_create' %}">
                        <img src="{% static 'market/new.png' %}" alt="Novo" />
                    </a>
                </th>
            </tr>
        </thead>
        {% for product in product_list %}
            <tbody>
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.average_cost }}</td>
                    <td>
                        <a href="{% url 'stock:product_update' product.id %}">
                            <img src="{% static 'market/edit.png' %}" alt="Editar"/>
                        </a>
                    </td>
                </tr>
            </tbody>
        {% endfor %}
    </table>
{% endblock %}

market/stock/templates/stock/purchase_form.html
{% extends 'market/base.html' %}

{% block pagetitle %}
    {% if purchase %}
        Editar compra
    {% else %}
        Nova compra
    {% endif %}
{% endblock %}


{% block content %}
    <h3>
        {% if purchase %}
            Editar compra
        {% else %}
            Nova compra
        {% endif %}
    </h3>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Salvar" />
    </form>

    <a href="{% url 'stock:purchase_index' %}" class="cancel">Cancelar</a>
{% endblock %}

market/stock/templates/stock/purchase_list.html
{% extends 'market/base.html' %}
{% load static %}

{% block pagetitle %}Compras{% endblock %}

{% block content %}

<table>
    <thead>
        <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Custo por item</th>
            <th>
                <a href="{% url 'stock:purchase_create' %}">
                    <img src="{% static 'market/new.png' %}" alt="Novo" />
                </a>
            </th>
        </tr>
    </thead>
    {% for purchase in purchase_list %}
        <tbody>
            <tr>
                <td>
                    <a href="{% url 'stock:product_index' %}">
                        {{ purchase.product.name }}
                    </a>    
                </td>
                <td>{{ purchase.amount }}</td>
                <td>{{ purchase.cost_per_item }}</td>
                <td>
                    <a href="{% url 'stock:purchase_update' purchase.id %}">
                        <img src="{% static 'market/edit.png' %}" alt="Editar"/>
                    </a>
                </td>
            
            </tr>
        </tbody>
    {% endfor %}
</table>
{% endblock %}